### PR TITLE
Enforce use of node version specified in .nvmrc

### PR DESCRIPTION
**Pull request by shumuko**

### CODE REVIEW

**Comment by grantovich** [comment]
Looks like CI is alerting us to some gem security issues, unrelated to this PR. I can bump those versions over the weekend if no one gets to them today.

**Comment by grantovich** [comment]
Regarding this addition, good idea! 😸 Couple suggestions:

1. It seems the latest LTS release is `6.10.1` rather than `6.10.0`, we should probably use that.

2. Currently Circle is set to use Node 5 in `circle.yml`, we should update that to 6 to keep things consistent. Although, I think they already use NVM so it should be possible to convince them to pick up the correct version from the `.nvmrc`, removing the duplication.

**Comment by shumuko** [comment]
We probably need another `.nvmrc` in the root directory too?

**Comment by grantovich** [comment]
Hopefully not, otherwise it will still be duplicated, just in a different place 😅 I was envisioning some sort of `nvm use` line added to the Circle file, but off-hand I'm not sure whether that will work with the way Circle runs the commands. If it ends up being complicated we can just change the version number in the Circle file and live with the duplication for now.

**Comment by shumuko** [comment]
Updated `.nvmrc` and `circle.yml`

**Comment by grantovich** [comment]
It seems I don't have permissions to give an official "approval" but looks good :shipit:

**Pull request merged**
